// <auto-generated />
using System;
using Cnss.Metier.CommunicationInterne.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommunicationInterne.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommunicationInterneDbContext))]
    [Migration("20260616143801_AjouterCritereGroupeDynamique")]
    partial class AjouterCritereGroupeDynamique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("communication_interne")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.DestinataireCible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("MessageInterneId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("MessageInterneId");

                    b.ToTable("MessageDestinataires", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.DossierDiffusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateLancement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeclencheurId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageInterneId")
                        .HasColumnType("uuid");

                    b.Property<int>("NombreDestinatairesTotaux")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DateLancement");

                    b.HasIndex("MessageInterneId");

                    b.ToTable("DossiersDiffusion", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.GroupeDiffusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateurId")
                        .HasColumnType("uuid");

                    b.Property<string>("CritereType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CritereValeur")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TypeGroupe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.HasIndex("Nom");

                    b.ToTable("Groupes", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.HistoriqueVoie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiePar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TypeVoie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("VoieCommunicationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Canal");

                    b.HasIndex("VoieCommunicationId", "DateAction");

                    b.ToTable("HistoriquesVoie", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.LigneDiffusion", b =>
                {
                    b.Property<Guid>("DossierDiffusionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Canal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageErreur")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("DossierDiffusionId", "AgentId", "Canal");

                    b.HasIndex("AgentId");

                    b.HasIndex("Statut");

                    b.ToTable("LignesDiffusion", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MembreGroupe", b =>
                {
                    b.Property<Guid>("GroupeDiffusionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupeDiffusionId", "AgentId");

                    b.HasIndex("AgentId");

                    b.ToTable("MembresGroupe", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MessageInterne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuteurId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuteurNom")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDiffusion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateProgrammee")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstArchive")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstInstitutionnel")
                        .HasColumnType("boolean");

                    b.Property<string>("MotiDeRejet")
                        .HasColumnType("text");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("ValidateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("Statut");

                    b.ToTable("Messages", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.PieceJointe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageInterneId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("TailleOctets")
                        .HasColumnType("bigint");

                    b.Property<string>("TypeMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MessageInterneId");

                    b.ToTable("PiecesJointes", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.VoieCommunication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgentIdRh")
                        .HasColumnType("integer");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgentIdRh")
                        .IsUnique();

                    b.HasIndex("Matricule");

                    b.ToTable("VoiesCommunication", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.VoieEmail", b =>
                {
                    b.Property<Guid>("VoieCommunicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("VoieCommunicationId", "Type");

                    b.ToTable("VoiesEmail", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.VoieTelephone", b =>
                {
                    b.Property<Guid>("VoieCommunicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("VoieCommunicationId", "Type");

                    b.ToTable("VoiesTelephone", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Infrastructure.Persistence.Configurations.MessageGroupeDestinataireEntry", b =>
                {
                    b.Property<Guid>("MessageInterneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupeId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageInterneId", "GroupeId");

                    b.HasIndex("GroupeId");

                    b.ToTable("MessageGroupesDestinataires", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Infrastructure.Persistence.Configurations.MessageInterneCanalEntry", b =>
                {
                    b.Property<Guid>("MessageInterneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Canal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MessageInterneId", "Canal");

                    b.ToTable("MessageCanaux", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.Shared.Domain.HistoriqueAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinataireId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DestinataireNom")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("EntiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntiteType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EtatApres")
                        .HasColumnType("text");

                    b.Property<string>("EtatAvant")
                        .HasColumnType("text");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UtilisateurNom")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UtilisateurRole")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DateAction");

                    b.HasIndex("EntiteType", "EntiteId");

                    b.ToTable("historique_actions", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.DestinataireCible", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MessageInterne", null)
                        .WithMany()
                        .HasForeignKey("MessageInterneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.HistoriqueVoie", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.VoieCommunication", null)
                        .WithMany("Historique")
                        .HasForeignKey("VoieCommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.LigneDiffusion", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.DossierDiffusion", null)
                        .WithMany("Lignes")
                        .HasForeignKey("DossierDiffusionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MembreGroupe", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.GroupeDiffusion", null)
                        .WithMany("Membres")
                        .HasForeignKey("GroupeDiffusionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.PieceJointe", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MessageInterne", null)
                        .WithMany()
                        .HasForeignKey("MessageInterneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.VoieEmail", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.VoieCommunication", null)
                        .WithMany("Emails")
                        .HasForeignKey("VoieCommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.VoieTelephone", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.VoieCommunication", null)
                        .WithMany("Telephones")
                        .HasForeignKey("VoieCommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Infrastructure.Persistence.Configurations.MessageGroupeDestinataireEntry", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MessageInterne", null)
                        .WithMany()
                        .HasForeignKey("MessageInterneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Infrastructure.Persistence.Configurations.MessageInterneCanalEntry", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MessageInterne", null)
                        .WithMany()
                        .HasForeignKey("MessageInterneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.DossierDiffusion", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.GroupeDiffusion", b =>
                {
                    b.Navigation("Membres");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.VoieCommunication", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("Historique");

                    b.Navigation("Telephones");
                });
#pragma warning restore 612, 618
        }
    }
}
