// <auto-generated />
using System;
using Cnss.Metier.CommunicationInterne.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cnss.Metier.CommunicationInterne.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommunicationInterneDbContext))]
    partial class CommunicationInterneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("communication_interne")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.DossierDiffusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateLancement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeclencheurId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageInterneId")
                        .HasColumnType("uuid");

                    b.Property<int>("NombreDestinatairesTotaux")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DateLancement");

                    b.HasIndex("MessageInterneId");

                    b.ToTable("DossiersDiffusion", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.GroupeDiffusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateurId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TypeGroupe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.HasIndex("Nom");

                    b.ToTable("Groupes", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.LigneDiffusion", b =>
                {
                    b.Property<Guid>("DossierDiffusionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Canal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageErreur")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("DossierDiffusionId", "AgentId", "Canal");

                    b.HasIndex("AgentId");

                    b.HasIndex("Statut");

                    b.ToTable("LignesDiffusion", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MembreGroupe", b =>
                {
                    b.Property<Guid>("GroupeDiffusionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupeDiffusionId", "AgentId");

                    b.HasIndex("AgentId");

                    b.ToTable("MembresGroupe", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MessageInterne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuteurId")
                        .HasColumnType("uuid");

                    b.Property<string>("Corps")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDiffusion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateProgrammee")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstArchive")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstInstitutionnel")
                        .HasColumnType("boolean");

                    b.Property<string>("MotiDeRejet")
                        .HasColumnType("text");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("ValidateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("Statut");

                    b.ToTable("Messages", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Infrastructure.Persistence.Configurations.MessageInterneCanalEntry", b =>
                {
                    b.Property<Guid>("MessageInterneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Canal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MessageInterneId", "Canal");

                    b.ToTable("MessageCanaux", "communication_interne");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.LigneDiffusion", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.DossierDiffusion", null)
                        .WithMany("Lignes")
                        .HasForeignKey("DossierDiffusionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MembreGroupe", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.GroupeDiffusion", null)
                        .WithMany("Membres")
                        .HasForeignKey("GroupeDiffusionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Infrastructure.Persistence.Configurations.MessageInterneCanalEntry", b =>
                {
                    b.HasOne("Cnss.Metier.CommunicationInterne.Domain.Aggregats.MessageInterne", null)
                        .WithMany()
                        .HasForeignKey("MessageInterneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.DossierDiffusion", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("Cnss.Metier.CommunicationInterne.Domain.Aggregats.GroupeDiffusion", b =>
                {
                    b.Navigation("Membres");
                });
#pragma warning restore 612, 618
        }
    }
}
